version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: heitor-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: heitor123
      MONGO_INITDB_DATABASE: heitor-bot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - heitor-network

  # Heitor Bot
  heitor:
    build: .
    container_name: heitor-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:heitor123@mongodb:27017/heitor-bot?authSource=admin
      - MONGODB_DB_NAME=heitor-bot
      - HEITOR_NAME=Heitor
      - OWNER_NAME=Andrey
      - OWNER_PHONE=5511999999999
      - OWNER_EMAIL=andrey@exemplo.com
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AI_PROVIDER=openai
      - OPENAI_MODEL=gpt-4
      - OPENAI_MAX_TOKENS=1000
      - OPENAI_TEMPERATURE=0.7
      - WHATSAPP_SESSION_PATH=./sessions
      - WHATSAPP_QR_CODE_PATH=./qr-code.png
      - WHATSAPP_HEADLESS=true
      - LOG_LEVEL=info
      - AUTO_START_HEITOR=true
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./qr-code.png:/app/qr-code.png
    depends_on:
      - mongodb
    networks:
      - heitor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (opcional, para cache)
  redis:
    image: redis:7-alpine
    container_name: heitor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - heitor-network

  # Nginx (opcional, para proxy reverso)
  nginx:
    image: nginx:alpine
    container_name: heitor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - heitor
    networks:
      - heitor-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  heitor-network:
    driver: bridge 